baseURL = "https://bitdevs-athens.com/"
languageCode = 'en-us'
title = 'BitDevs Athens'
theme = 'gokarna'
publishDir = 'docs'

[menu]
  [[menu.main]]
    name = "Seminars"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "<span data-feather='eye'></span>"
    url = "/about/"
    weight = 2
    [menu.main.params]
            target= "_self"


[params]
    avatarURL = "bitcoin.png"
    avatarSize = "size-l"
    description = "Socratic seminars focusing on technical aspect of bitcoin"
    description2 = "Next seminar: Monday 3 April, 7pm @ Yodeck"
    footer = "bitdevs-athens"
    socialIcons = [
      {name = "email", url = "https://www.meetup.com/blockchaingreece-0/"},
    ]
