title: 'BitDevs Athens'
tagline: 'BitDevs is a community for those interested in discussing and participating in the research and development of Bitcoin and related protocols.'

menu:
  - {name: 'About', url: '/about'}
  - {name: 'Events', url: '/events'}
  - {name: 'Meetup', url: 'https://www.meetup.com/blockchaingreece-0', external: true}

social:
  - {icon: 'github', link: 'https://github.com/bitdevs-athens'}
  - {icon: 'twitter', link: 'https://twitter.com/BitDevsAthens'}
  - {icon: 'meetup', link: 'https://www.meetup.com/blockchaingreece-0'}
